/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZombieScreenIndexRouteImport } from './routes/zombieScreen/index'
import { Route as PickYourZombieScreenIndexRouteImport } from './routes/pickYourZombieScreen/index'
import { Route as ExerciseScreenIndexRouteImport } from './routes/exerciseScreen/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZombieScreenIndexRoute = ZombieScreenIndexRouteImport.update({
  id: '/zombieScreen/',
  path: '/zombieScreen/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickYourZombieScreenIndexRoute =
  PickYourZombieScreenIndexRouteImport.update({
    id: '/pickYourZombieScreen/',
    path: '/pickYourZombieScreen/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExerciseScreenIndexRoute = ExerciseScreenIndexRouteImport.update({
  id: '/exerciseScreen/',
  path: '/exerciseScreen/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exerciseScreen/': typeof ExerciseScreenIndexRoute
  '/pickYourZombieScreen/': typeof PickYourZombieScreenIndexRoute
  '/zombieScreen/': typeof ZombieScreenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exerciseScreen': typeof ExerciseScreenIndexRoute
  '/pickYourZombieScreen': typeof PickYourZombieScreenIndexRoute
  '/zombieScreen': typeof ZombieScreenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exerciseScreen/': typeof ExerciseScreenIndexRoute
  '/pickYourZombieScreen/': typeof PickYourZombieScreenIndexRoute
  '/zombieScreen/': typeof ZombieScreenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exerciseScreen/'
    | '/pickYourZombieScreen/'
    | '/zombieScreen/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exerciseScreen' | '/pickYourZombieScreen' | '/zombieScreen'
  id:
    | '__root__'
    | '/'
    | '/exerciseScreen/'
    | '/pickYourZombieScreen/'
    | '/zombieScreen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExerciseScreenIndexRoute: typeof ExerciseScreenIndexRoute
  PickYourZombieScreenIndexRoute: typeof PickYourZombieScreenIndexRoute
  ZombieScreenIndexRoute: typeof ZombieScreenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zombieScreen/': {
      id: '/zombieScreen/'
      path: '/zombieScreen'
      fullPath: '/zombieScreen/'
      preLoaderRoute: typeof ZombieScreenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickYourZombieScreen/': {
      id: '/pickYourZombieScreen/'
      path: '/pickYourZombieScreen'
      fullPath: '/pickYourZombieScreen/'
      preLoaderRoute: typeof PickYourZombieScreenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exerciseScreen/': {
      id: '/exerciseScreen/'
      path: '/exerciseScreen'
      fullPath: '/exerciseScreen/'
      preLoaderRoute: typeof ExerciseScreenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExerciseScreenIndexRoute: ExerciseScreenIndexRoute,
  PickYourZombieScreenIndexRoute: PickYourZombieScreenIndexRoute,
  ZombieScreenIndexRoute: ZombieScreenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
